# Generated by Django 5.0.13 on 2025-12-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Taller',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('preferencia_contacto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id_mecanico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('certificado', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Mecánico',
                'verbose_name_plural': 'Mecánicos',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id_repuesto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_repuesto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('id_proveedor_repuesto', models.IntegerField()),
                ('num_pieza_fabricante', models.CharField(max_length=50)),
                ('compatibilidad_vehiculos', models.TextField()),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
            },
        ),
        migrations.CreateModel(
            name='Orden_Reparacion',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida_estimada', models.DateField()),
                ('estado_orden', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50)),
                ('diagnostico_inicial', models.TextField()),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('id_mecanico_asignado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_asignadas', to='app_automovil.mecanico')),
            ],
            options={
                'verbose_name': 'Orden de Reparación',
                'verbose_name_plural': 'Órdenes de Reparación',
            },
        ),
        migrations.CreateModel(
            name='Factura_Taller',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('total_factura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('iva_aplicado', models.DecimalField(decimal_places=2, default=16.0, max_digits=5)),
                ('id_cliente_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='app_automovil.cliente_taller')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='app_automovil.orden_reparacion')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Reparacion',
            fields=[
                ('id_detalle_rep', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_repuesto', models.IntegerField()),
                ('precio_repuesto_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mano_obra_horas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costo_mano_obra_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_automovil.orden_reparacion')),
                ('id_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_automovil.repuesto')),
            ],
            options={
                'verbose_name': 'Detalle de Reparación',
                'verbose_name_plural': 'Detalles de Reparación',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo_Taller',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('matricula', models.CharField(max_length=20)),
                ('num_chasis', models.CharField(max_length=50)),
                ('kilometraje_entrada', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('estado_general', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='app_automovil.cliente_taller')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.AddField(
            model_name='orden_reparacion',
            name='id_vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='app_automovil.vehiculo_taller'),
        ),
    ]
